default_stages: [pre-commit]
repos:
  - repo: https://github.com/rcmdnk/pyproject-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff-lint-diff
        stages: [pre-commit]
      - id: ruff-lint
        stages: [pre-commit]
      - id: ruff-format-diff
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]
        #- id: mypy
        #  stages: [pre-commit]
      - id: dmypy
        stages: [pre-commit]
      - id: numpydoc-validation
        stages: [pre-commit]
      - id: shellcheck
        stages: [pre-commit]
      - id: mdformat-check
        stages: [pre-commit]
      - id: mdformat
        stages: [pre-commit]
      # models is not included in check
      #- id: actionlint
      #  stages: [pre-commit]
      - id: validate-pyproject
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-byte-order-marker
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-case-conflict
        stages: [pre-commit]
      - id: check-merge-conflict
        args:
          - "--assume-in-merge"
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: fix-byte-order-marker
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: debug-statements
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]
      - id: detect-aws-credentials
        args:
          - "--allow-missing-credentials"
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: combine
        name: combine
        language: system
        entry: uv run ./combine.sh
        pass_filenames: false
        always_run: true
        stages: [pre-push]
      - id: pytest-version
        name: pytest-version
        language: system
        entry: uv run pytest ./tests/test_version.py
        pass_filenames: false
        always_run: true
        stages: [pre-push]
