language: objective-c
#language: python
os: osx
# Python version is not available for OSX
# [Python runtime is not yet available on OS X · Issue #2312 · travis-ci/travis-ci](https://github.com/travis-ci/travis-ci/issues/2312)
#python:
#  - "2.7"
#  - "3.5"
branches:
  except:
    - /^v[0-9]/
env:
  global:
    - GIT_COMMITTER_NAME=rcmdnk
    - GIT_COMMITTER_EMAIL=rcmdnk@gmail.com
    - GIT_AUTHOR_NAME=rcmdnk
    - GIT_AUTHOR_EMAIL=rcmdnk@gmail.com
    - PAGER=cat
    - EDITOR=cat # for brew-file edit test
    - VISUAL=cat
    - coveralls=coveralls-python
    #- coveralls=python-coveralls
  matrix:
    - PYTHON_VERSION="python"
    - PYTHON_VERSION="python3"
before_install:
  #- '[ "$TRAVIS_PULL_REQUEST" = "false" ] && openssl aes-256-cbc -K $encrypted_43fa9741277b_key -iv $encrypted_43fa9741277b_iv -in .travis_rsa.enc -out .travis_rsa -d || :'
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$PYTHON_VERSION" = "python" ] && openssl aes-256-cbc -K $encrypted_63171a4b9582_key -iv $encrypted_63171a4b9582_iv -in .travis_rsa_$PYTHON_VERSION.enc -out .travis_rsa_$PYTHON_VERSION -d || :'
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$PYTHON_VERSION" = "python3" ] && openssl aes-256-cbc -K $encrypted_d679fce5eb37_key -iv $encrypted_d679fce5eb37_iv -in .travis_rsa_$PYTHON_VERSION.enc -out .travis_rsa_$PYTHON_VERSION -d || :'
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && cp .travis_rsa_$PYTHON_VERSION ~/.ssh/id_rsa || :'
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && chmod 600 ~/.ssh/id_rsa || :'
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config || :'
  - version=""
  - 'if [ $TRAVIS_BRANCH = master ];then version="--HEAD";elif [ $TRAVIS_BRANCH = bash ];then version="--bash";fi'
  - brew update
install:
  - testaccount=rcmdnk
  - testreponame=BrewfileTest
  - testrepo=$testaccount/$testreponame
  - testrepodir=${testaccount}_${testreponame}
  - testrepofulldir=$HOME/.brewfile/$testrepodir
  - testfile=$testrepofulldir/Brewfile
  - sw_vers
  - brew list > brewlist.orig
  - brew install rcmdnk/file/brew-file $version
  - brew tap homebrew/dupes # needed, as current travis environment is old and has some packages which are now under dupes, but travis environment doesn't have dupes tap.
  - cd ../
  - git clone git@github.com:$testrepo
  - cd $testreponame
  - cp ../homebrew-file/BrewfileTest ./Brewfile
  - cp ../homebrew-file/BrewfileExt ./BrewfileExt
  - cp ../homebrew-file/BrewfileHome ~/BrewfileHome
  - git add -A && git commit -a -m "init" && git push -f || echo nothing to be done
  - cd ../homebrew-file
  - rm -rf ../$testrepo
before_script:
  - installed_brew=$(which brew-file)
  - brewprefix=$(brew --prefix)
  - brewfile=$HOME/.brewfile/Brewfile
  - exe=$(pwd)/bin/brew-file
  - git config --global push.default simple # to suppress git warning
script:
  # Check differences between checked out's version and brew installed version
  - '[ "$version" != "" ] && diff $installed_brew $exe || :'
  - '[ "$version" != "" ] && brew file help | ( $exe help | diff /dev/fd/3 -) 3<&0 || :'
  - '[ "$version" != "" ] && brew file version | ( $exe version | diff /dev/fd/3 -) 3<&0 || :'
  # Check with old Python (expect 2.7.5)
  - python --version
  - 'coverage run --parallel-mode $exe brew install tig --HEAD --with-docs | :' # old version can't use hyphen options at brew file brew.
  # Install the latest version of Python
  - rm -rf /usr/local/lib/python2.7/site-packages
  - rm -rf /usr/local/bin/easy_install
  - rm -rf /usr/local/bin/easy_install-2.7
  - rm -rf /usr/local/bin/pip
  - rm -rf /usr/local/bin/pip2
  - rm -rf /usr/local/bin/pip2.7
  - brew install $PYTHON_VERSION
  - '[ "$PYTHON_VERSION" = "python3" ] && rm -f /usr/local/bin/python && ln -s /usr/local/bin/python3 /usr/local/bin/python || :'
  - '[ "$PYTHON_VERSION" = "python3" ] && rm -f /usr/local/bin/pip && ln -s /usr/local/bin/pip3 /usr/local/bin/pip || :'
  - python --version
  - hash -r
  - python --version
  - which python
  - which pip
  - type pip
  - pip install --upgrade pip
  - '[ "$coveralls" = "coveralls-python" ] && pip install coveralls || :'
  - '[ "$coveralls" = "python-coveralls" ] && pip -e . --use-mirrors || :'
  # Sanity checks
  - coverage run --parallel-mode $exe version
  - coverage run --parallel-mode $exe help
  - coverage run --parallel-mode $exe commands
  - 'coverage run --parallel-mode $exe || :'
  - coverage run --parallel-mode $exe brew list >/dev/null
  - mkdir -p $(dirname "$brewfile")
  - touch "$brewfile"
  - coverage run --parallel-mode $exe init -y
  - coverage run --parallel-mode $exe update -y -V 2 # better to use verbose mode, because the update takes so long time that travis will end up with no output error if no output is written out at update...
  - coverage run --parallel-mode $exe test -V 2
  - coverage run --parallel-mode $exe install --no_appstore --preupdate -y
  - rm $brewfile
  - coverage run --parallel-mode $exe update -y
  # brew command checks
  - coverage run --parallel-mode $exe brew help
  - coverage run --parallel-mode $exe brew noinit list
  - coverage run --parallel-mode $exe brew info bash
  - coverage run --parallel-mode $exe brew install wget --HEAD --with-iri
  - coverage run --parallel-mode $exe init -y -V 0
  - coverage run --parallel-mode $exe brew uninstall wget
  - coverage run --parallel-mode $exe brew tap rcmdnk/mytest
  - coverage run --parallel-mode $exe brew tap rcmdnk/mytest
  - coverage run --parallel-mode $exe brew install mytest2
  - coverage run --parallel-mode $exe brew install mytest2
  - coverage run --parallel-mode $exe brew rm mytest2
  - coverage run --parallel-mode $exe brew untap rcmdnk/mytest
  - coverage run --parallel-mode $exe brew install rcmdnk/mytest/mytest2
  - coverage run --parallel-mode $exe brew install rcmdnk/mytest/mytest2
  - coverage run --parallel-mode $exe brew tap rcmdnk/mytest
  - coverage run --parallel-mode $exe brew rm mytest2
  - cat $brewfile |grep -v mytest > ${brewfile}.tmp
  - mv ${brewfile}{.tmp,}
  - coverage run --parallel-mode $exe brew untap rcmdnk/mytest
  - coverage run --parallel-mode $exe brew install rcmdnk/mytest/mytest2 --HEAD
  - 'coverage run --parallel-mode $exe brew untap rcmdnk/notexist || :'
  - coverage run --parallel-mode $exe brew cask install appcleaner
  - coverage run --parallel-mode $exe brew cask install appcleaner
  - coverage run --parallel-mode $exe brew cask rm appcleaner
  - command brew cask install appcleaner
  - coverage run --parallel-mode $exe brew cask rm appcleaner
  - coverage run --parallel-mode $exe brew install brew-pip
  - coverage run --parallel-mode $exe brew pip asciinema
  - coverage run --parallel-mode $exe brew uninstall pip-asciinema
  - coverage run --parallel-mode $exe brew pip -u django==1.2
  - coverage run --parallel-mode $exe brew rm brew-pip
  - coverage run --parallel-mode $exe brew install brew-gem
  - coverage run --parallel-mode $exe brew gem install heroku
  - coverage run --parallel-mode $exe brew gem uninstall heroku
  - coverage run --parallel-mode $exe brew gem install heroku 3.8.3
  - coverage run --parallel-mode $exe brew gem uninstall heroku
  - 'coverage run --parallel-mode $exe brew wrong_cmd -V 0|| :'
  # Cask tests
  - coverage run --parallel-mode $exe brew cask install firefox
  # can't use for python3...?
  #- coverage run --parallel-mode $exe brew install macvim # Application installed by brew command, instead of cask
  - coverage run --parallel-mode $exe brew cask list
  - coverage run --parallel-mode $exe edit
  - coverage run --parallel-mode $exe casklist -V 2
  - coverage run --parallel-mode $exe brew untap caskroom/cask
  - coverage run --parallel-mode $exe casklist -V 0
  - coverage run --parallel-mode $exe cask_upgrade -C -V 0
  - command brew cask rm firefox
  - coverage run --parallel-mode $exe cask_upgrade -C -V 0
  - command brew cask install firefox
  - mv /Applications/Firefox.app .
  - command brew cask rm firefox
  - mv Firefox.app /Applications/
  - coverage run --parallel-mode $exe casklist -V 0
  - export HOMEBREW_CASK_OPTS="--appdir=~/Applications --caskroom=/opt/homebrew-cask/Caskroom"
  - coverage run --parallel-mode $exe cask_upgrade -V 0
  - export HOMEBREW_CASK_OPTS="cask_opt_error_test"
  - 'coverage run --parallel-mode $exe brew noupdate help >/dev/null || :'
  - export HOMEBREW_CASK_OPTS="--appdir=~/Applications --caskroom=/opt/homebrew-cask/Caskroom"
  - coverage run --parallel-mode $exe casklist -V 0
  # Wrong file/command tests
  - 'coverage run --parallel-mode $exe -f BrewfileWrong pull -y -V 0 || :'
  - 'coverage run --parallel-mode $exe -f BrewfileWrong --no_appstore install -y -V 0 || :'
  - 'coverage run --parallel-mode $exe wrongcommand || :'
  # Wrong command test (test proc)
  - echo 'ls wrong_file' > $brewfile
  - 'coverage run --parallel-mode $exe install --no_appstore || :'
  # Use test repository
  - coverage run --parallel-mode $exe set_repo -r git://github.com/$testrepo -y -V 2
  - rm -rf $brewfile $testrepofulldir
  - coverage run --parallel-mode $exe set_repo -r git@github.com:$testrepo -y -V 2
  - rm -rf $brewfile $testrepofulldir
  - coverage run --parallel-mode $exe set_repo -r https://github.com/$testrepo -y -V 2
  - rm -rf $brewfile $testrepofulldir
  - coverage run --parallel-mode $exe init -r $testrepo -y -V 2
  - rm -rf $brewfile $testrepofulldir
  - coverage run --parallel-mode $exe set_repo -r $testrepo -y -V 2
  - coverage run --parallel-mode $exe set_repo -r $testrepo -y -V 2
  - coverage run --parallel-mode $exe get_files
  - coverage run --parallel-mode $exe edit
  - cp $testfile .
  - coverage run --parallel-mode $exe brew tap rcmdnk/mytest
  - coverage run --parallel-mode $exe --no_appstore install -V 2
  - coverage run --parallel-mode $exe casklist -V 0
  - command brew rm emacs
  - coverage run --parallel-mode $exe init -y -V 0
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && coverage run --parallel-mode $exe update -y -U -V 2'
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && coverage run --parallel-mode $exe update -y'
  - coverage run --parallel-mode $exe brew rm wget
  - command brew cask install google-chrome
  - coverage run --parallel-mode $exe casklist -V 2
  - cp Brewfile $testfile
  - coverage run --parallel-mode $exe brew untap rcmdnk/rcmdnkcask
  - coverage run --parallel-mode $exe casklist -V 0
  # brewdler format tests
  - coverage run --parallel-mode $exe init -F brewdler -y -V 2
  - coverage run --parallel-mode $exe install --no_appstore -F brewdler
  - echo "appstore 'KeyNotes'" >> $testfile
  - echo "file 'BrewfileExt'" >> $testfile
  - coverage run --parallel-mode $exe -F brewdler brew cask uninstall google-chrome
  - cat /Users/travis/.brewfile/rcmdnk_$testreponame/Brewfile
  # command format tests
  - coverage run --parallel-mode $exe init -F command -y -V 2
  - coverage run --parallel-mode $exe install --no_appstore -F command
  # Clean up tests
  - echo "brew brew-file $version" > $testfile
  - echo "brew python" >> $testfile
  - echo "brew python3" >> $testfile
  - echo "file BrewfileExt" >> $testfile
  - echo "brew bash" >> $testfile
  - while read p;do echo "brew $p" >> $testfile;done < brewlist.orig
  - coverage run --parallel-mode $exe clean
  - coverage run --parallel-mode $exe brew cask list
  - $exe get_files
  - cat $($exe get_files)
  - coverage run --parallel-mode $exe clean -C
  - coverage run --parallel-mode $exe init -y -V 2
  - coverage run --parallel-mode $exe brew cask install firefox
  - coverage run --parallel-mode $exe clean -C
  # Wrong command test
  - echo "wrong command" > $testfile
  - 'coverage run --parallel-mode $exe install --no_appstore | :'
  # Push current Brewfile in homebrew-file to BrewfileTest
  - cp Brewfile $testfile
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && coverage run --parallel-mode $exe push -V 0'
  # Test with brew-wrap
  - source $(brew --prefix)/etc/brew-wrap
  - type brew
  - brew list
  - brew install hub
  - brew noinit install stow
  # send coverage result to coveralls
  - coverage combine # should be done before removing brew-file
  - coveralls
  # Install test
  #- rm -rf $brewprefix/bin/brew $HOME/.brewfile $brewprefix/Cellar
  #- rm -rf $brewprefix/.git*
  #- curl -fsSL https://raw.github.com/rcmdnk/homebrew-file/install/install.sh |sh >&/dev/null
  #- brew help
  #- brew file help
notifications:
  email:
    recipients:
      - rcmdnk@gmail.com
    on_success: change
    on_failure: always

