language: objective-c
os: osx
# xcode9: macOS Sierra 10.12, xcode7.3: OS X El Capitan 10.11
# [Building an Objective-C Project - Travis CI](https://docs.travis-ci.com/user/languages/objective-c/)
# can't be multiple definition?
#osx_image:
#  - xcode9
#  - xcode 7.3
osx_image: xcode9
# Python version is not available for OSX
# [Python runtime is not yet available on OS X · Issue #2312 · travis-ci/travis-ci](https://github.com/travis-ci/travis-ci/issues/2312)
#language: python
#python:
#  - "2.7"
#  - "3.5"
branches:
  except:
    - /^v[0-9]/
env:
  global:
    - GIT_COMMITTER_NAME=rcmdnk
    - GIT_COMMITTER_EMAIL=rcmdnk@gmail.com
    - GIT_AUTHOR_NAME=rcmdnk
    - GIT_AUTHOR_EMAIL=rcmdnk@gmail.com
    - PAGER=cat
    - EDITOR=cat # for brew-file edit test
    - VISUAL=cat
    - coveralls=coveralls-python
    #- coveralls=python-coveralls
    - CONFIGDIR="$HOME/.config/brewfile"
  matrix:
    - PYTHON_VERSION="python2"
    - PYTHON_VERSION="python3"
before_install:
  - echo $TRAVIS_PULL_REQUEST
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ];then echo pull request test; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ];then openssl aes-256-cbc -K $encrypted_63171a4b9582_key -iv $encrypted_63171a4b9582_iv -in test/.travis_rsa.tar.enc -out .travis_rsa.tar -d; tar xvf .travis_rsa.tar; mv .travis_rsa_python .travis_rsa_python2; cp .travis_rsa_$PYTHON_VERSION ~/.ssh/id_rsa; chmod 600 ~/.ssh/id_rsa; echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config; fi'
  - sw_vers
  - brew --version
  - brew update
  - brew --version
install:
  - git config --global user.email "$GIT_AUTHOR_EMAIL"
  - git config --global user.name "$GIT_AUTHOR_NAME"
  - testaccount=rcmdnk
  - testreponame=BrewfileTest_$PYTHON_VERSION
  - testrepo=$testaccount/$testreponame
  - testrepodir=${testaccount}_${testreponame}
  - testrepofulldir=$CONFIGDIR/$testrepodir
  - testfile=$testrepofulldir/Brewfile
  - brew list > brewlist.orig
  - brew install rcmdnk/file/brew-file
  - cd ../
  - echo $TRAVIS_PULL_REQUEST
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ];then echo TRAVIS_PULL_REQUEST test; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ];then git clone git@github.com:$testrepo;else git clone https://github.com/$testrepo; fi'
  - cd $testreponame
  - cp ../homebrew-file/test/BrewfileTest ./Brewfile
  - cp ../homebrew-file/test/BrewfileExt ./BrewfileExt
  - cp ../homebrew-file/test/BrewfileHome ~/BrewfileHome
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ];then git add -A && git commit -a -m "init" && git push -f || echo nothing to be done; fi'
  - cd ../homebrew-file
  - rm -rf ../$testrepo
  - which python
  - python --version
  - 'brew rm --ignore-dependencies  mercurial || :'
  - 'brew rm --ignore-dependencies python || :'
  - 'brew rm --ignore-dependencies python2 || :'
  - 'brew install $PYTHON_VERSION || :'
  - 'ls -l /usr/local/lib/python2.7/site-packages/numpy/ || :'
  - pip list
  - hash -r
  - 'brew upgrade $PYTHON_VERSION || :'
  - export PATH="$(brew --prefix)/opt/$PYTHON_VERSION/libexec/bin:$PATH"
  - '[ "$PYTHON_VERSION" = "python2" ] &&  pip install virtualenv|| :'
  - '[ "$PYTHON_VERSION" = "python2" ] &&  virtualenv -p python py_env|| :'
  - '[ "$PYTHON_VERSION" = "python3" ] &&  python -m venv py_env|| :'
  - pip list
  - source py_env/bin/activate
  - python --version
  - which python
  - which pip
  - type pip
  - pip install --upgrade pip
  - '[ "$coveralls" = "coveralls-python" ] && pip install coveralls || :'
  - '[ "$coveralls" = "python-coveralls" ] && pip -e . --use-mirrors || :'
  - pip list
  - which ruby
  - brew install ruby
  - hash -r
  - which ruby
  - which gem
before_script:
  - installed_brew=$(which brew-file)
  - brewprefix=$(brew --prefix)
  - brewfile=$CONFIGDIR/Brewfile
  - exe=$(pwd)/bin/brew-file
  - git config --global push.default simple # to suppress git warning
script:
  # Sanity checks
  - coverage run --parallel-mode $exe version
  - coverage run --parallel-mode $exe help
  - coverage run --parallel-mode $exe commands
  - 'coverage run --parallel-mode $exe || :'
  - coverage run --parallel-mode $exe brew list >/dev/null
  - mkdir -p $(dirname "$brewfile")
  - touch "$brewfile"
  - brew list
  - coverage run --parallel-mode $exe init -y
  - coverage run --parallel-mode $exe cat
  - pip list
  - 'ls -l /usr/local/lib/python2.7/site-packages/numpy/ || :'
  - brew rm postgis
  - brew rm gdal
  - brew rm numpy
  - 'ls -l /usr/local/lib/python2.7/site-packages/numpy/ || :'
  - coverage run --parallel-mode $exe update -y -V 2 # better to use verbose mode, because the update takes so long time that travis will end up with no output error if no output is written out at update...
  - pip list
